### ISSUE TITLE
Epic: Consistent Formatting

### ISSUE THREAD

**Issue by phanimarupaka** [kptdev/kpt#2108]
**Phase 1: For beta2 release**

- [x] Preserve field ordering. (https://github.com/kubernetes-sigs/kustomize/pull/4021)
- [x] Preserve sequence node indentation.
- [x] Disable formatting for eval and render commands.

Solves issues:
https://github.com/GoogleContainerTools/kpt/issues/2104
https://github.com/GoogleContainerTools/kpt/issues/2101
https://github.com/GoogleContainerTools/kpt/issues/2332
https://github.com/GoogleContainerTools/kpt/issues/2342
https://github.com/GoogleContainerTools/kpt/issues/2068

**Phase 2: Long term**
- [ ]  Design proposal when and how to format resources. (https://github.com/GoogleContainerTools/kpt/issues/2349)
- [ ] Implement the items in approved proposal.
- [ ] Related user issues (https://github.com/GoogleContainerTools/kpt/issues/2404, https://github.com/GoogleContainerTools/kpt/issues/2383, https://github.com/GoogleContainerTools/kpt/issues/2405)

**Comment by mikebz** [comment]
@phanimarupaka is phase1 finished up with beta2 release?

**Comment by phanimarupaka** [comment]
> @phanimarupaka is phase1 finished up with beta2 release?

Yes.

**Comment by CsatariGergely** [comment]
Most of this work was still done.
