### ISSUE TITLE
EPIC: Improve imperative user experience for setters

### ISSUE THREAD

**Issue by phanimarupaka** [kptdev/kpt#2485]
- [ ] Update the documentation for create-setters function with best practices on how to use the function.
- [ ] list-setters function should list the setter information per package similar to pre-v1. Currently all setters are listed as if they belong to the single root package.
- [ ] Setters with same name might have same or different values based on the semantics of the setter. We should formulate a good UX to record the intent of package consumers in order to set the values. E.g. Consider `cluster(rootpkg)` and `nodepool(subpkg)`. If both have `project-id` setter, they both mean the same and should have the same value. On the other hand, if there is a setter called `name` in both packages, even though the setter name is same, `cluster.name` and `nodepool.name` should NOT have same value.

cc @pitta @droot

**Comment by Pitta** [comment]
> list-setters function should list the setter information per package similar to pre-v1. Currently all setters are listed as if they belong to the single root package.

I think perhaps this should be the default output, but should have flags to produce what is currently being used. With perhaps more to adjust the output for yaml, etc.

>  Setters with same name might have same or different values based on the semantics of the setter. We should formulate a good UX to record the intent of package consumers in order to set the values. E.g. Consider cluster(rootpkg) and nodepool(subpkg). If both have project-id setter, they both mean the same and should have the same value. On the other hand, if there is a setter called name in both packages, even though the setter name is same, cluster.name and nodepool.name should NOT have same value.

I may be reading this incorrectly, but wanted to expand on this a bit.
There is an additional case to consider which is pulling in and having multiple copies of the same `nodepool(subpkg)`. This will produce multiple instances of setters like `nodepool.name` that should all be unique in their values.

**Comment by phanimarupaka** [comment]
> > list-setters function should list the setter information per package similar to pre-v1. Currently all setters are listed as if they belong to the single root package.
> 
> I think perhaps this should be the default output, but should have flags to produce what is currently being used. With perhaps more to adjust the output for yaml, etc.
> 
> > Setters with same name might have same or different values based on the semantics of the setter. We should formulate a good UX to record the intent of package consumers in order to set the values. E.g. Consider cluster(rootpkg) and nodepool(subpkg). If both have project-id setter, they both mean the same and should have the same value. On the other hand, if there is a setter called name in both packages, even though the setter name is same, cluster.name and nodepool.name should NOT have same value.
> 
> I may be reading this incorrectly, but wanted to expand on this a bit.
> There is an additional case to consider which is pulling in and having multiple copies of the same `nodepool(subpkg)`. This will produce multiple instances of setters like `nodepool.name` that should all be unique in their values.

Yes. In this case, the intent is to have different value even the setter name is same. The general idea is to obtain the intent of the user for knowing the semantics of setters with same name across packages.

**Comment by Pitta** [comment]
`kpt fn eval -i create-setters:v0.1 --fn-config `
Tab completion for the file paths here (and in various other places too numerous to enumerate at the moment) would be very helpful.
